[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Redirect rules for Astro
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404 